language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 1.0.4
    - os: osx
      osx_image: xcode8
      dotnet: 1.0.4

before_script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then sudo apt-get install libc6-dev; fi

script:
  - dotnet --info
  - ./build.sh
